#ifndef CONFIG_H
#define CONFIG_H

#include <stdint.h>

#define DEFAULT_MOISTURE_LOW 30.0f
#define DEFAULT_MOISTURE_HIGH 45.0f
#define DEFAULT_WATERING_MAX_MS (30 * 1000) // 30s
#define DEFAULT_SENSOR_CYCLE_MS (5 * 60 * 1000) // 5 minutes
#define DEFAULT_MIN_INTERVAL_MS (10 * 60 * 1000) // 10 minutes

/*<! Value for Simulate */
#define SIMULATED_SENSOR_CYCLE_MS (5 * 1000) // 5s
#define SIMULATED_MIN_INTERVAL_MS (15 * 1000) // 15s
#define SIMULATED_WATERING_MAX_MS (10 * 1000) // 10s
#define SIMULATED_MOISTURE_SOIL  40.0f
#define SIMLUATED_ENVIROMENT_TEMPURATURE 30.0f

#define AVERAGE_DATA_MOISTURE 4
#define AVERAGE_DATA_TEMPURATURE 4

#endif // CONFIG_H

